CREATE TABLE coords_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
    notes VARCHAR(255),
    lat DECIMAL(10, 8),
    lng DECIMAL(11, 8),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);